add_newline = true
scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
# min_time = 500
format = "underwent [$duration](bold yellow)"

[git_branch]
# symbol = "🌱 "
# truncation_length = 18
# truncation_symbol = "…"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[python]
pyenv_version_name = true

[nodejs]
disabled = true

[docker_context]
disabled = true
format = "via [🐋 $context](blue bold) "

[git_commit]
# commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# [username]
# style_user = "white bold"
# style_root = "black bold"
# format = "user: [$user]($style) "
# disabled = false
# show_always = true

